name: Feature request
description: Propose an enhancement
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Feature summary
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
